### ISSUE TITLE
Clipboard is not accessible in overlay

### ISSUE THREAD

**Issue by chetanchoudhary08** [moazelsawaf/dash_bubble#12] opened 2023-10-29 13:29 UTC
I am trying to get some data from the clipboard but I am getting `null` while I am sure the data is present in clipboard and tested that.

**Comment by chetanchoudhary08** [comment] 2023-10-29 14:05
It is working in **Physical Device**, was not working in **Emulator**.

**Comment by moazelsawaf** [comment] 2023-10-30 01:00
Hello @chetanchoudhary08 👋🏻

I'm glad to hear that the issue is resolved! However, I'm going to reopen it in order to better understand why it was not working in the **Emulator**. I would be grateful if you could share a minimal reproducing code for the issue, or at least the exact scenario and steps that did not work for you 🙏🏻

**Comment by chetanchoudhary08** [comment] 2023-10-30 05:11
Actually the problem was not related to whether the device is an **Emulator** or  a **Physical Device**. The problem was in the **Android API** version. I was testing with a physical device with `Android 9` and some emulators with `Android 10+`.

Starting from `Android 10`, there are some privacy changes which limits the use of clipboard, hence, I was having issue accessing clipboard in emulator.

Reference Article: [Access clipboard data in the background service in Android 10 (Q)](https://codingwithsaud.medium.com/access-clipboard-data-in-the-background-service-in-android-10-q-d2f445c12ab3)

**Comment by moazelsawaf** [comment] 2023-10-30 05:59
Thanks for sharing that 👌🏻

I am happy that you understand the issue and have some references to go with 🙏🏻

Since the issue is not related to the package, I am going to close it as completed ✅

**Closed as completed** 2023-10-30 05:59 UTC
Labels: invalid
